### PR TITLE
#975 FIX VCS comment query

### LINKED ISSUE #975: Comment minimization brings forward changes even if the PR no longer has them
### Describe the bug

On comment minimization, the new comment can include changes that no-longer exist in the PR.

### Steps to reproduce

1. Create a pull request with changes to dirs A and B.
2. Wait for plan, plan will have output for A and B.
3. Update the PR to no longer have changes to B.
4. Wait for plan

### Expected behavior

In (4), the output should only be for A, and not include B.

### Actual behavior

In (4), A and B are output.

### Terrateam version & environment details

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by schonfinkel**
## Description

- Closes #975

## Type of change

- [X] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation update
- [ ] Other (explain):

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/terrateamio/terrateam/blob/main/CONTRIBUTING.md)
- [x] The pull request title follows this format:
      `ISSUE_NUMBER ACTION_TYPE Short description` (e.g., `123 ADD Feature description`)
- [x] I have added tests and documentation (if applicable)
- [x] My changes generate no new warnings/errors and do not break existing functionality

### CODE REVIEW

File: code/src/terrat_files/github/sql/select_comment_elements.sql [hunk 1]
```diff
@@ -9,13 +21,18 @@ select
     wso.success,
     wso.step
 from github_work_manifest_comments gwmc
+-- Let's call it "WM1", i.e. the OLD WORK MANIFEST
```
Comment (orbitz) [inline code/src/terrat_files/github/sql/select_comment_elements.sql]: This is from our pairing, I think, but the name doesn't come up anywhere else in the query.  Maybe expand on it or delete it?

**Review by orbitz — DISMISSED** [review]

**Review by orbitz — APPROVED** [review]
